-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "languages" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "interests" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "emergencyContact" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "drivingYears" INTEGER;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "travelStyle" TEXT;
